### ISSUE TITLE
Panic with map[string]interface{} in configuration

### ISSUE THREAD

**Issue by jdub** [hashicorp/waypoint-plugin-sdk#4]
I tried to use a `map[string]interface{}` type in my plugin configuration, but the Waypoint CLI panics when parsing the attribute. Turns out there's an easily reproducible example [in the `aws_ami` plugin](https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ami/builder.go#L25-L38), using Waypoint v0.1.3 (cf5706e9):

```hcl
project = "pants"

app "pants" {
    build {
        use "aws-ami" {
            region = "ap-southeast-2"
            filters = {
                image-type: "machine"
                root-device-type: "ebs"
                virtualization-type: "hvm"
            }
        }
    }

    deploy {
		use "docker" {}
    }
}
```

```
$ waypoint init
✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "pants" and all apps are registered with the server.
⠙ Validating required plugins...panic: unsuitable DecodeExpression target: no cty.Type for interface {}

goroutine 14 [running]:
github.com/hashicorp/hcl/v2/gohcl.DecodeExpression(0x31986928, 0xc00096ab40, 0xc000f78400, 0x3861780, 0xc00098d378, 0xc00098d378, 0x195, 0x3ad5880)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:295 +0x978
github.com/hashicorp/hcl/v2/gohcl.decodeBodyToStruct(0x45bc860, 0xc000b9cc60, 0xc000f78400, 0xc00007cea0, 0xc00098d340, 0x199, 0x0, 0xc000441cb0, 0x0)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:111 +0x6ae
github.com/hashicorp/hcl/v2/gohcl.decodeBodyToValue(0x45bc860, 0xc000b9cc60, 0xc000f78400, 0xc00007cea0, 0xc00098d340, 0x199, 0xc00090f448, 0x1a91d7d, 0xc00020d180)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:43 +0xd9
github.com/hashicorp/hcl/v2/gohcl.DecodeBody(0x45bc860, 0xc000b9cc60, 0xc000f78400, 0xc00098d380, 0xc00098d340, 0x36afd01, 0x9, 0x0)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:36 +0xf0
github.com/hashicorp/waypoint-plugin-sdk/component.Configure(0x3cffa40, 0xc0005f9400, 0x45bc860, 0xc000b9cc60, 0xc000f78400, 0xc0005f00a8, 0x0, 0x1)
	/go/pkg/mod/github.com/hashicorp/waypoint-plugin-sdk@v0.0.0-20201016002013-59421183d54f/component/configure.go:63 +0xe8
github.com/hashicorp/waypoint/internal/core.(*App).initComponent(0xc0008d2540, 0x45bc0e0, 0xc00011cb00, 0xc000f78400, 0x1, 0x3832740, 0xc0008d2540, 0xc000f78da0, 0xc000ae3350, 0x0, ...)
	/home/circleci/project/waypoint/internal/core/app.go:373 +0x8da
github.com/hashicorp/waypoint/internal/core.newApp(0x45bc0e0, 0xc00011cb00, 0xc0002429c0, 0xc000384c30, 0xc000f78400, 0x1, 0xc0005d90e0, 0x12)
	/home/circleci/project/waypoint/internal/core/app.go:136 +0xc6c
github.com/hashicorp/waypoint/internal/core.NewProject(0x45bc0e0, 0xc00011cb00, 0xc00090fb78, 0xb, 0xb, 0x2, 0x0, 0x0)
	/home/circleci/project/waypoint/internal/core/project.go:131 +0x4db
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeJob(0xc0000fec00, 0x45bc0e0, 0xc00011cb00, 0x45f4da0, 0xc0003e73b0, 0x45db100, 0xc000f783c0, 0xc0005ee9c0, 0x0, 0x0, ...)
	/home/circleci/project/waypoint/internal/runner/operation.go:70 +0x69d
github.com/hashicorp/waypoint/internal/runner.(*Runner).accept(0xc0000fec00, 0x45bc0e0, 0xc00011cb00, 0xc0008b73a0, 0x1a, 0x0, 0x0)
	/home/circleci/project/waypoint/internal/runner/accept.go:213 +0x1565
github.com/hashicorp/waypoint/internal/runner.(*Runner).AcceptExact(...)
	/home/circleci/project/waypoint/internal/runner/accept.go:36
github.com/hashicorp/waypoint/internal/client.(*Project).doJob.func2.1(0xc00000e188, 0xc0000fec00, 0x45bc0e0, 0xc00098cb00, 0xc0008b73a0, 0x1a, 0x45f4da0, 0xc000766af0)
	/home/circleci/project/waypoint/internal/client/job.go:91 +0x8e
created by github.com/hashicorp/waypoint/internal/client.(*Project).doJob.func2
	/home/circleci/project/waypoint/internal/client/job.go:89 +0x105
```

**Comment by catsby** [comment]
Hey @jdub - I've tried to reproduce it using Waypoint v0.2.1 without success. I'm attempting to recent it with v0.1.3 as you mention but having trouble getting that environment recreated (not related to the error shown). Are you still encountering this issue?

**Comment by briancain** [comment]
@jdub Shouldn't your filter hash be defined as:

```hcl
use "aws-ami" {
            region = "ap-southeast-2"
            filters = {
                image-type = "machine"
                root-device-type = "ebs"
                virtualization-type = "hvm"
            }
        }
```

So essentially an `=` instead of a `:`? I think maybe the panic is a parse error here.

**Comment by briancain** [comment]
Also filters is a map of arrays, so it should be defined as:

```hcl
    filters = [{
                image-type = "machine"
                root-device-type = "ebs"
                virtualization-type = "hvm"
            },
            {
              // another filter here
            },
     ]
```

**Comment by briancain** [comment]
Hey there, I'm going to go ahead and close this given there hasn't been a response. I believe the fix I mentioned above should resolve the issue. I'm going to close this for now, but if you are still experiencing this issue, please feel free to leave a comment or open a new issue referencing this one. Thank you!
